### ISSUE TITLE
Inference on custom dataset with nano version

### ISSUE THREAD

**Issue by Alberto1404** [otamajakusi/yolov5-aws-lambda#1]
Hi, 
I would like to to inference of a custom yolov5 model using aws lambda. Could you provide a deep tutorial on how to do this?
Also, how to revive the process to avoid the 15 minutos limit?

**Comment by otamajakusi** [comment]
Hi,
Did you read read.me and this blog: https://i7y.org/en/how-to-use-yolov5-on-aws-lambda/
?
Or need dedicated support?

**Comment by otamajakusi** [comment]
What do you mean by `nano version`?

**Comment by Alberto1404** [comment]
> What do you mean by `nano version`?

Yolov5n



> Hi, Did you read read.me and this blog: https://i7y.org/en/how-to-use-yolov5-on-aws-lambda/ ? Or need dedicated support?

Didn't see that blog. Let me read it and I'll let you know. Basically I am super new at Lambda, and my task is to deploy a custom finetuned model 24/7. I heard about the limitation of the 15 minutes, and I was expecting to know a way to go beyond that (finish the call function and recall it again, automatically, or something, but I do not know whether this makes sense)

**Comment by otamajakusi** [comment]
Use step function to extend lambda timeout.
